# Generated by Django 4.0.5 on 2022-06-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto_remove_avatar_user_delete_clase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='montoAbonado',
            field=models.IntegerField(default=2500, max_length=200),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fechaPago',
            field=models.CharField(max_length=40),
        ),
    ]
