# Generated by Django 4.0.5 on 2022-06-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_pagos_montoabonado_alter_contacto_mensaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='montoAbonado',
            field=models.IntegerField(default=2500),
        ),
    ]
